# Generated by Django 6.0.6 on 2026-07-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
