# Generated by Django 6.0.6 on 2026-07-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_scheduleitem_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='alarm_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='card_type',
            field=models.CharField(choices=[('wake', '起床'), ('move', '移動'), ('eat', '食事'), ('see', '観光'), ('stay', '宿泊'), ('free', 'フリー')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='card_type',
            field=models.CharField(choices=[('wake', '起床'), ('move', '移動'), ('eat', '食事'), ('see', '観光'), ('stay', '宿泊'), ('free', 'フリー')], default='free', max_length=10),
        ),
    ]
