# Generated by Django 6.0.6 on 2026-07-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_travelplan_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
