# Generated by Django 6.0.6 on 2026-07-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_scheduleitem_approval_enabled_group_travelplan_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardresponse',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
