# Generated by Django 6.0.6 on 2026-07-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_cardresponse_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardresponse',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
