# Generated by Django 6.0.6 on 2026-07-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_cardresponse_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='cost_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='participant_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
