# Generated by Django 6.0.6 on 2026-07-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_scheduleitem_cost_scheduleitem_cost_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='warikan_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
