# Generated by Django 6.0.6 on 2026-07-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_travelplan_warikan_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitem',
            name='cost_participants',
        ),
    ]
