# Generated by Django 6.0.6 on 2026-07-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='from_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='to_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
