# Generated by Django 6.0.6 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_remove_travelplan_is_liked_planlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtemplate',
            name='card_type',
            field=models.CharField(choices=[('wake', '起床'), ('move', '移動'), ('eat', 'ご飯'), ('see', '観光'), ('stay', 'ホテル'), ('other', 'その他'), ('free', '予備')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='card_type',
            field=models.CharField(choices=[('wake', '起床'), ('move', '移動'), ('eat', 'ご飯'), ('see', '観光'), ('stay', 'ホテル'), ('other', 'その他'), ('free', '予備')], default='free', max_length=10),
        ),
    ]
