# Generated by Django 6.0.6 on 2026-08-08 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_editrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='chat_mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
