# Generated by Django 6.0.6 on 2026-08-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_groupmessage_edited_at_groupmessage_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
